spring:
  application:
    name: prefab.avro-example

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}

topics:
  customer.name: prefab.avro-example.customer
  sale.name: prefab.avro-example.sale

error.handling:
    exception-logging: WITH_STACKTRACE