spring:
  application:
    name: example
  cloud:
    gcp:
      project-id: example

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/prefab_example
    username: example
    password: example

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}
kafka:
  topics:
    sale:
      name: sale


logging.level:
  root: WARN
  be.appify.prefab.example: DEBUG